name: Build Static Site

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2 # Specify PHP version

      # Step 3: Install wget
      - name: Install wget
        run: sudo apt-get install -y wget

      # Step 4: Start PHP server and generate static files
      - name: Generate Static HTML
        run: |
          for file in $(find public -regex '.*\.php\|.*\.html\|.*\.css\|.*\.js\|.*\.png\|.*\.jpg\|.*\.gif\|.*\.ico)'); do
            relative_path=$(realpath --relative-to=public "$file" | sed s/.php$/.html/)
            mkdir -p "dist/$(dirname $relative_path)"
            php.exe -f $file | sed s/.php/.html/gm >> dist/$relative_path
          done

          for file in $(find dist -regex '.*template\.html'); do
            rm "$file"
          done

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          cname: www.antonwittig.de
          force_orphan: true
